# Generated by Django 4.0.5 on 2022-07-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinamodel',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
