# Generated by Django 4.0.6 on 2022-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='url_documento',
            field=models.FileField(storage='relatorios/', upload_to=''),
        ),
    ]
