# Generated by Django 4.0.6 on 2022-08-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinamodel',
            name='relatorio',
        ),
        migrations.AddField(
            model_name='relatoriomodel',
            name='disciplina',
            field=models.ManyToManyField(to='core.disciplinamodel'),
        ),
    ]
