# Generated by Django 4.0.6 on 2022-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'ativo'), (2, 'desativado')], default=1),
        ),
    ]
