# Generated by Django 4.0.5 on 2022-07-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Email_Administrativo')], default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvisoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('email_origem', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailadministrativo')),
                ('usuario_destinatario', models.ManyToManyField(to='core.alunomodel')),
                ('usuario_remetente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adminmodel')),
            ],
        ),
    ]
