# Generated by Django 3.2.6 on 2022-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuariomodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinamodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativa'), (2, 'Inativa')], default=1),
        ),
    ]
