# Generated by Django 4.0.5 on 2022-07-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailadministrativo_avisomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisomodel',
            old_name='usuario_destinatario',
            new_name='aluno',
        ),
    ]
