# Generated by Django 4.0.6 on 2022-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_relatoriomodel_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriomodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'aberto'), (2, 'fechado')], default=1),
        ),
    ]
