# Generated by Django 4.0.6 on 2022-09-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_documentmodel_url_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
