# Generated by Django 4.0.6 on 2022-09-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_documentmodel_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relatoriomodel'),
        ),
    ]
