# Generated by Django 4.0.6 on 2022-07-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_assinaturamodel_url_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturamodel',
            name='url_assinatura',
            field=models.ImageField(upload_to='media/uploads/'),
        ),
    ]
